name: Build iOS IPA
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: 显示所有文件（查看真实路径）
        run: ls -la

      - name: 安装 XcodeGen
        run: brew install xcodegen

      - name: 生成 Xcode 项目
        run: xcodegen generate

      - name: 编译打包
        run: xcodebuild archive -project "企业应用.xcodeproj" -scheme "企业应用" -archivePath app.xcarchive

      - name: 导出 IPA
        run: xcodebuild -exportArchive -archivePath app.xcarchive -exportPath output -exportOptionsPlist ExportOptions.plist

      - name: 上传 IPA 安装包
        uses: actions/upload-artifact@v4
        with:
          name: EnterpriseApp
          path: output/
